[package]
name = "ssemu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baby-emulator = "0.1.4"
clap = { version = "4.3.23", features = ["derive"] }

